/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacoursework1;

/**
 *
 * @author Rizwana Sadaf
 */
public class from2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form from2
     */
    public from2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        close = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"101", "\"Shape of You\"", "Ed Sheeran",  new Integer(2017)},
                {"102", "\"That's What I Like\"", "Bruno Mars",  new Integer(2017)},
                {"103", "\"I'm the One\"", "DJ Khaled featuring Justin Bieber, Quavo,  Chance the Rapper and Lil Wayne",  new Integer(2017)},
                {"104", "\"Despacito\"", "Luis Fonsi and Daddy Yankee featuring Justin Bieber",  new Integer(2017)},
                {"105", "	\"Look What You Made Me Do\"", "Taylor Swift",  new Integer(2017)},
                {"106", "\"Bodak Yellow\"", "Cardi B",  new Integer(2017)},
                {"107", "\"Rockstar\"", "Post Malone featuring 21 Savage",  new Integer(2017)},
                {"108", "\"Perfect\"", "Ed Sheeran duet with Beyoncé",  new Integer(2017)},
                {"109", "\"Hello\"", "Adele",  new Integer(2016)},
                {"110", "\"Sorry\"", "Justin Bieber",  new Integer(2016)},
                {"111", "\"Love Yourself\"", "Justin Bieber",  new Integer(2016)},
                {"112", "\"Work\"", "	Rihanna featuring Drake",  new Integer(2016)},
                {"113", "\"Can't Stop the Feeling!\"", "Justin Timberlake",  new Integer(2016)},
                {"114", "\"One Dance\"", "Drake featuring Wizkid and Kyla",  new Integer(2016)},
                {"115", "\"Cheap Thrills\"", "Sia featuring Sean Paul",  new Integer(2016)},
                {"116", "\"Closer\"", "The Chainsmokers featuring Halsey",  new Integer(2016)},
                {"114", "\"Black Beatles\"", "Rae Sremmurd featuring Gucci Mane",  new Integer(2016)}
            },
            new String [] {
                "SongID", "SongName", "Singer", "ReleasedYear"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        close.setText("Cancel");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       this.hide();
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
